### ISSUE TITLE
Does not work with latest 1Password 6.3.1 (or iTem2 3.0.0?)

### ISSUE THREAD

**Issue by michaelbutler** [ravenac95/sudolikeaboss#24] opened 2016-06-09 20:20 UTC
sudolikeaboss was working great for me for a while but it seemed to break recently. Can anyone confirm whether 1Password 6.3.1 is supported and working? I figure it may be possible that 1Password 6 changed something in their API that blocked off using this tool.

I'm on:
1Password 6.3.1 (latest)
iTerm 2 3.0.0 (latest)
Mac OS X 10.11.5 (El Capitan)

**Comment by bensherman** [comment] 2016-06-09 22:08
Dupe of https://github.com/ravenac95/sudolikeaboss/issues/19

**Comment by nomaddesign** [comment] 2016-06-10 08:27
#19 has been closed, but has the binary been updated?  The version number is still 0.2.0 in the repo and binary.    I tried removing / installing with brew and didn't see any difference.

**Comment by ravenac95** [comment] 2016-06-10 23:10
Hey guys, I've been delayed at work. Didn't anticipate as much work coming back from vacation. Homebrew installs should now work! Let me know if there's an issue.

**Closed by ravenac95** 2016-06-10 23:10 UTC
